#!/bin/sh

. ./common.sh

# ensure that our build directories exist
mkdir -p $OBJDIR $OUTDIR

# template our library header
cp version.gen.h $INCDIR/version.h
sed -i "s/@VERSION_PATCH@/$PATCH/g" $INCDIR/version.h
sed -i "s/@VERSION_MINOR@/$MINOR/g" $INCDIR/version.h
sed -i "s/@VERSION_MAJOR@/$MAJOR/g" $INCDIR/version.h
sed -i "s/@VERSION@/\"$VERSION\"/g" $INCDIR/version.h

# perform the unity build
$CC $CFLAGS -I$INCDIR -c -o $OBJDIR/$TARGET.o $SRCDIR/unity_build.c

# build the static library
$AR crs $OUTDIR/$STATIC $OBJDIR/$TARGET.o
$RANLIB $OUTDIR/$STATIC

# build the shared library
$LD $LDFLAGS -I$INCDIR -shared -o $OUTDIR/$SHARED $OBJDIR/$TARGET.o
