#!/bin/sh

. ./common.sh

# create include path
mkdir -p ${DESTDIR}${PREFIX}/include/$TARGET
cp -rf $INCDIR/* ${DESTDIR}${PREFIX}/include/$TARGET

# copy over versioned archive and create convenience symlink
cp -p $OUTDIR/$STATIC ${DESTDIR}${PREFIX}/lib
ln -sf $TARGET.a.$MAJOR ${DESTDIR}${PREFIX}/lib/$TARGET.a
ln -sf $STATIC ${DESTDIR}${PREFIX}/lib/$TARGET.a.$MAJOR

# copy over versioned shared object and create convenience symlink
cp $OUTDIR/$SHARED ${DESTDIR}${PREFIX}/lib
ln -sf $TARGET.so.$MAJOR ${DESTDIR}${PREFIX}/lib/$TARGET.so
ln -sf $SHARED ${DESTDIR}${PREFIX}/lib/$TARGET.so.$MAJOR
