#!/bin/sh

. ./common.sh

# clean out stale tests
[ -d $OUTDIR/$TESTS ] && rm -r $OUTDIR/$TESTS
mkdir $OUTDIR/$TESTS

# compile then run each test, printing results to screen
for TEST_SRC in $(find $TESTS/ -name '*.c'); do
	EXE="$(basename $TEST_SRC .c)"
	$CC $CFLAGS -I$TESTS -I$INCDIR -L$OUTDIR -l$TARGET.$VERSION -o $OUTDIR/$TESTS/$EXE $TEST_SRC

	LD_LIBRARY_PATH=$OUTDIR $OUTDIR/$TESTS/$EXE
done
